#!/bin/bash

source ~/.config/hypr/lib.sh

window=settings

current_info=$(eww-rice windows | grep "$window")

if [[ $current_info == "*$window" ]]; then
	eww-rice close $window
else
	eww-rice open $window
fi
